### ISSUE TITLE
Cover research software

### ISSUE THREAD

**Issue by rvosa** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#35]
There is very little about research software, and quite a lot about generic open source (understandable, because there is more material to borrow from). As examples of open source software, we name LibreOffice and FireFox, which don't make the case at all: most people use Microsoft Office and Chrome, and the alternatives seem like, well, alternatives. What we need to discuss here, I think, is actual open source software used in research, such as R and Rstudio, python tools, QGIS, basically all of the bioinformatics tools, etc. and point out the culture that surrounds them, where scientists develop tools and libraries, and publish them.

**Comment by Protohedgehog** [comment]
Awesome, thanks @rvosa! You're totally right about this. I suggest adding in a section after 'Existing software' dedicated to this (https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md#table-of-contents). We can perhaps focus on some generic ones, such as R and Python, and then delve into a few discipline specific ones, and try and cover a nice range there.

**Comment by Protohedgehog** [comment]
@rvosa Have this now :) https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/MAIN.md#Research

**Comment by alexmorley** [comment]
Wonder whether we could go for something like this. Thoughts?

---

**I'm using X[e.g. Matlab,STATA,Excel] and I want to transition to something more open. What are the next steps?**
Even if you are using proprietary software, you can usually still share your source code/documents etc. *The best first step is sharing whatever you can*.
**Great! I can put them in my new github repo.**  

 If that's enough for you for now great! If not for most pieces of proprietary software there are Open Source equivalents. Have a go with one and see what you think.

| Closed | Open |
| --- | --- |
| Matlab | Python, Julia |
| STATA/SPSS | R |
| MS Office | Libre Office |
| etc... | etc... |

**Cool! But if I make the switch will I be stuck: taking ages to learn a new tool/ without support /with buggy software.**
Good question! The answer is it depends. The best thing to do is find someone who's made the switch before and learn from their experience. Or just do a google search! Some OSS is much better than their closed counterparts, some aren't, so it's worth choosing carefully.

**Comment by Protohedgehog** [comment]
HOLY MOLY YES PLEASE. Thank goodness for smart/creative people..

**Comment by rvosa** [comment]
Or this: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/commit/2e1ba5cc84d55b69b42f2d6faa76151d83c4bf63#diff-0f8e0b24775d666f702b75d530494cf9

**Comment by Protohedgehog** [comment]
Cannot express how happy I am to see these contributions right now.. Thank you, @rvosa and @alexmorley! I'm sure there is a way to combine them both. I love Alex' idea of a sort of FAQ too.

**Comment by rvosa** [comment]
I like @alexmorley's suggestion but I think it would be quite an enterprise, and really dependent on the specific research field. For example, just for the most generic workflows of "next-generation" DNA sequencing analysis, there's like dozens of single-purpose open source utilities to choose from to do the basic data processing even before you're attempting anything interesting. I imagine this is true in many fields.

**Comment by Protohedgehog** [comment]
Yes, this is true @rvosa - however, I don't think we need to be exhaustive in this respect. Provide some examples of cross-disciplinary software, and then a few well-known ones that are discipline specific. I think that will be enough to get people thinking about these things more. And we can add a simple statement like that others exist for other fields, and could be sought out where required.

**Comment by jcolomb** [comment]
Would be interesting to have a third column stating where the guys who maintain/develop the tool get money from (firefox gets most of it from google, libreoffice gets it through donation (I think), Better gets it by selling an easy to install version of their open source software,…..)

Should we start a google sheet ? (we can then use Rmd to create the up top date html file for the mooc).




Dr. Julien Colomb
#openscience #neuroscience
https://orcid.org/0000-0002-3127-5520
Trainer at access2perspectives.com
Founder of Drososhare.net

Schillerpromenade 4
12049 Berlin

**Comment by dannycolin** [comment]
@jcolomb I don't know if that third column is really a good idea. I mean there's a difference between Mozilla Corporation and Mozilla Foundation. 

Also, LibreOffice via the Document Foundation benefit from big corporation like Google, Intel and Amd. I mean every big free and open source projects receive money from big corporations.

Moreover, it could create bias in users choice. For example, if I want to avoid Google because I don't want to support corporations that don't respect online privacy doesn't that mean I should avoid Non-profit who receive money from Google.

**Comment by gschivley** [comment]
Here's a good matlab to Python guide. I'm not recommending an Enthought installation of Python (I use conda for package and environment management) but it's a short-ish document that might be helpful.

https://www.enthought.com/wp-content/uploads/Enthought-MATLAB-to-Python-White-Paper.pdf

**Comment by jcolomb** [comment]
Since one of the objective is to understand the economy of open source software, these questions are relevant, a third column might not be the most effective way to deal with the question, though. Any other suggestion?

PS: I personally make no difference between for-profit and non-for-profit software companies. I would be more confident to use a product from a for profit company which states its objective and business model, than a non-profit whose income or product is dependent to companies I dislike/showed bad behaviour in the past (remember using software dependent on the google rss software !)
  
Dr. Julien Colomb
#openscience #neuroscience
https://orcid.org/0000-0002-3127-5520
Trainer at access2perspectives.com
Founder of Drososhare.net

Schillerpromenade 4
12049 Berlin

**Comment by Protohedgehog** [comment]
Did we settle on a conclusion for this in the end? I think @alexmorley's idea of a little table, and the engaging Q&A text would be a perfect compliment to what @rvosa has already written.

**Comment by alexmorley** [comment]
There's a PR now if people want to comment or make changes :)

I really like @jcolomb's idea but I think because the issue is far from simple I'd rather give it its own section (maybe or maybe not in the core material) or point to some detailed discussion than add a column in the table where it could add some confusion (at least it would for pea-brained folk such as myself!).

Happy friday y'all!

**Comment by trallard** [comment]
I like the idea of @alexmorley table. I think it a great yet concise way to communicate the general idea.

**Comment by Protohedgehog** [comment]
This is awesome, thanks so much @alexmorley! Have a great weekend all, I think this is a nice way to round off the week :)

**Comment by jcolomb** [comment]
Hey, sorry to reopen, but what about creating a curated list of OOS for researchers.
we could use this as a start (but put the information in a spreadsheet !): https://gist.github.com/stared/9130888
or is there another list @bmkramer ?

(others are trying to build such lists, see: https://docs.google.com/spreadsheets/d/1pYjIPXbuObf3V3RXTQ7pJeYF73HI_5o1CCdPXJDtbX8/edit#gid=0)

**Comment by dannycolin** [comment]
@jcolomb would you like something more interactive (e.g alternativeto.net). It should be easy to do with jekyll (or any static site generator). 

Also have a look at https://directory.fsf.org/wiki/Category/Science. It's probably a bit outdated but it's a wiki so anyone can contribute to it.

**Comment by Protohedgehog** [comment]
Can/should this be closed for now?

**Comment by jcolomb** [comment]
updates, see  https://github.com/OpenScienceMOOC/opendatabase
(sorry @Protohedgehog can reopen but not close the issue :) )
