### ISSUE TITLE
Finish Task 2, integrating GitHub and Zenodo

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source#7]
Development here: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_2.Rmd

**Comment by Protohedgehog** [comment]
The first draft of this task has now been completed, and is open for more feedback!

**Comment by mrchristian** [comment]
Second draft done. The end Zenodo bit is very tricky as Zenodo gets complicated and I feel you need to let people know what site they should be working on: GitHub, Zenodo.

Obviously pics will help here as with GitHub's version.

There are obviously things that are not too good in the Zenodo system. But hey.

I would suggest another proof and handing to a couple of newbies to see if the instructions work.

**Comment by Protohedgehog** [comment]
Yes, I think images will help a lot here. Will get around to adding them shortly.

**Comment by npch** [comment]
Some nice work here - kudos!

As another pro tip, adding your preferred citation to your README.md further lowers the barrier to other people citing your work. If you're using the GitHub to Zenodo integration this is really easy as you can use their "Cite As" widget to create different styles (or just copy the default).

If you think this would be a good thing to add, I'll do a PR.

**Comment by Protohedgehog** [comment]
Hey @npch! Thanks for this comment. Within the task itself, that pro tip is already included here: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/Task_2.md#getting-a-doi- - is this what you mean?

Thinking out loud, do you think it's worth doing for this module for now and creating a first release too..?

**Comment by npch** [comment]
Hi @Protohedgehog - if it's the pro tip which is:

> Copy the URL for the DOI into the README file for your GitHub repo to make cross-linking even easier, as well as present a clear highlighted DOI badge for users to see and make use of your DOI. You only need to do this once with your first release DOI as it acts as a 'concept DOI' and is linked to all subsequent release DOIs.

then not entirely. What I'm suggesting is that you put in the README.md a little section which says (something like):

## Citing this software

If you've used our software in your research, please use the following citation:

Jon Tennant. (2018, July 30). Foundations for Open Scholarship Strategy Development: First formal release (Version 1.2). Zenodo. http://doi.org/10.5281/zenodo.1323437

**Comment by Protohedgehog** [comment]
I get you! But..and it might just be me..isn't this for the Open Scholarship Strategy? Or are you just using this as an example for this MOOC module..? I'm sensing crossed streams, but if you mean create a citation like this for each module, that will definitely be done at some point in the very near future! We could even make the first release for this module, like, now.. :)

**Comment by npch** [comment]
Crossed streams :-)

What I meant was that in general, as part of open scholarship I think if you write software you should:

1. Use a code repository
2. Deposit your code and get a DOI
3. Make it as easy as possible for people to understand how to cite your software

The first part of Step 3 is making sure you put the DOI for the software you've just deposited in Zenodo in your README, but an additional step is to either put the "human-readable" version (I used your Open Scholarship Strategy as an example, but basically for whichever software you've deposited) in your README, particularly for researchers who are not as familiar with using DOIs to create citations in their preferred styles. 

This is because I think open scholarship will only thrive if we acknowledge that our research builds on other people's work, and the current way that we do this is through citations. So making it easy for others to cite your software isn't just something selfish to help you (although that's a plus), it's also helping to show the interconnectedness and value around having an open community.

**Comment by npch** [comment]
But yes, I also think it's worth having a preferred citation for each module as well so that people can cite your MOOC materials as well :-D

**Comment by Protohedgehog** [comment]
AHA! OK, I totally get you now. Awesome idea, sorry for being so slow. Have done this now for the strategy: https://github.com/Open-Scholarship-Strategy/site#citing-this-software and will make this as a separate protip for Task 2 here in a second. Thanks for taking the time to explain this for me :)

And great re. the MOOC, I'll make a first release for this module after making the edits! Exciting :)
